version: 2
ethernets:
  eth0:
    dhcp4: false
    dhcp6: false
    addresses:
      - 192.168.0.20/24
    gateway4: 192.168.0.1
    nameservers:
      search: [home]
      addresses: [8.8.8.8, 8.8.4.4]
